[project]
name = "henry-viii"
version = "1.0.0"
description = "The service from Henry VIII."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"